/*
 * IntelliMob, an intelligent plugin to give AI to Java Minecraft Bedrock servers
 * Copyright (C) 2021  José Roberto de Araújo Júnior <joserobjr@powernukkit.org>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

package games.joserobjr.intellimob.entity

import cn.nukkit.entity.Entity.*

/**
 * @author joserobjr
 * @since 2021-01-22
 */
internal actual enum class EntityFlag(val id: Int, val container: Int = if (id > 64) DATA_FLAGS_EXTENDED else DATA_FLAGS) {
    ON_FIRE(DATA_FLAG_ONFIRE),
    SNEAKING(DATA_FLAG_SNEAKING),
    RIDING(DATA_FLAG_RIDING),
    SPRINTING(DATA_FLAG_SPRINTING),
    ACTION(DATA_FLAG_ACTION),
    INVISIBLE(DATA_FLAG_INVISIBLE),
    TEMPTED(DATA_FLAG_TEMPTED),
    IN_LOVE(DATA_FLAG_INLOVE),
    SADDLED(DATA_FLAG_SADDLED),
    POWERED(DATA_FLAG_POWERED),
    IGNITED(DATA_FLAG_IGNITED),
    BABY(DATA_FLAG_BABY),
    CONVERTING(DATA_FLAG_CONVERTING),
    CRITICAL(DATA_FLAG_CRITICAL),
    CAN_SHOW_NAMETAG(DATA_FLAG_CAN_SHOW_NAMETAG),
    ALWAYS_SHOW_NAMETAG(DATA_FLAG_ALWAYS_SHOW_NAMETAG),
    IMMOBILE(DATA_FLAG_IMMOBILE),
    SILENT(DATA_FLAG_SILENT),
    WALL_CLIMBING(DATA_FLAG_WALLCLIMBING),
    CAN_CLIMB(DATA_FLAG_CAN_CLIMB),
    SWIMMER(DATA_FLAG_SWIMMER),
    CAN_FLY(DATA_FLAG_CAN_FLY),
    CAN_WALK(DATA_FLAG_WALKER),
    RESTING(DATA_FLAG_RESTING),
    SITTING(DATA_FLAG_SITTING),
    ANGRY(DATA_FLAG_ANGRY),
    INTERESTED(DATA_FLAG_INTERESTED),
    CHARGED(DATA_FLAG_CHARGED),
    TAMED(DATA_FLAG_TAMED),
    ORPHANED(DATA_FLAG_ORPHANED),
    LEASHED(DATA_FLAG_LEASHED),
    SHEARED(DATA_FLAG_SHEARED),
    GLIDING(DATA_FLAG_GLIDING),
    ELDER(DATA_FLAG_ELDER),
    MOVING(DATA_FLAG_MOVING),
    BREATHING(DATA_FLAG_BREATHING),
    CHESTED(DATA_FLAG_CHESTED),
    STACKABLE(DATA_FLAG_STACKABLE),
    SHOWBASE(DATA_FLAG_SHOWBASE),
    REARING(DATA_FLAG_REARING),
    VIBRATING(DATA_FLAG_VIBRATING),
    IDLING(DATA_FLAG_IDLING),
    EVOKER_SPELL(DATA_FLAG_EVOKER_SPELL),
    CHARGE_ATTACK(DATA_FLAG_CHARGE_ATTACK),
    WASD_CONTROLLED(DATA_FLAG_WASD_CONTROLLED),
    CAN_POWER_JUMP(DATA_FLAG_CAN_POWER_JUMP),
    LINGER(DATA_FLAG_LINGER),
    HAS_COLLISION(DATA_FLAG_HAS_COLLISION),
    HAS_GRAVITY(DATA_FLAG_GRAVITY),
    FIRE_IMMUNE(DATA_FLAG_FIRE_IMMUNE),
    DANCING(DATA_FLAG_DANCING),
    ENCHANTED(DATA_FLAG_ENCHANTED),
    SHOW_TRIDENT_ROPE(DATA_FLAG_SHOW_TRIDENT_ROPE),
    CONTAINER_PRIVATE(DATA_FLAG_CONTAINER_PRIVATE),
    IS_TRANSFORMING(DATA_FLAG_IS_TRANSFORMING),
    SPIN_ATTACK(DATA_FLAG_SPIN_ATTACK),
    SWIMMING(DATA_FLAG_SWIMMING),
    BRIBED(DATA_FLAG_BRIBED),
    PREGNANT(DATA_FLAG_PREGNANT),
    LAYING_EGG(DATA_FLAG_LAYING_EGG),
    RIDER_CAN_PICKUP(DATA_FLAG_RIDER_CAN_PICK),
    @Suppress("DEPRECATION")
    TRANSITION_SITTING(DATA_FLAG_TRANSITION_SITTING),
    EATING(DATA_FLAG_EATING),
    LAYING_DOWN(DATA_FLAG_LAYING_DOWN),
    SNEEZING(DATA_FLAG_SNEEZING),
    TRUSTING(DATA_FLAG_TRUSTING),
    ROLLING(DATA_FLAG_ROLLING),
    SCARED(DATA_FLAG_SCARED),
    IN_SCAFFOLDING(DATA_FLAG_IN_SCAFFOLDING),
    OVER_SCAFFOLDING(DATA_FLAG_OVER_SCAFFOLDING),
    FALL_THROUGH_SCAFFOLDING(DATA_FLAG_FALL_THROUGH_SCAFFOLDING),
    BLOCKING(DATA_FLAG_BLOCKING),
    TRANSITION_BLOCKING(DATA_FLAG_TRANSITION_BLOCKING),
    BLOCKED_USING_SHIELD(DATA_FLAG_BLOCKED_USING_SHIELD),
    BLOCKED_USING_DAMAGED_SHIELD(DATA_FLAG_BLOCKED_USING_DAMAGED_SHIELD),
    SLEEPING(DATA_FLAG_SLEEPING),
    WANTS_TO_WAKE(DATA_FLAG_WANTS_TO_WAKE),
    TRADE_INTEREST(DATA_FLAG_TRADE_INTEREST),
    DOOR_BREAKER(DATA_FLAG_DOOR_BREAKER),
    BREAKING_OBSTRUCTION(DATA_FLAG_BREAKING_OBSTRUCTION),
    DOOR_OPENER(DATA_FLAG_DOOR_OPENER),
    IS_ILLAGER_CAPTAIN(DATA_FLAG_IS_ILLAGER_CAPTAIN),
    STUNNED(DATA_FLAG_STUNNED),
    ROARING(DATA_FLAG_ROARING),
    DELAYED_ATTACK(DATA_FLAG_DELAYED_ATTACK),
    IS_AVOIDING_MOBS(DATA_FLAG_IS_AVOIDING_MOBS),
    IS_AVOIDING_BLOCKS(DATA_FLAG_IS_AVOIDING_BLOCKS),
    FACING_TARGET_TO_RANGE_ATTACK(DATA_FLAG_FACING_TARGET_TO_RANGE_ATTACK),
    HIDDEN_WHEN_INVISIBLE(DATA_FLAG_HIDDEN_WHEN_INVISIBLE),
    IS_IN_UI(DATA_FLAG_IS_IN_UI),
    STALKING(DATA_FLAG_STALKING),
    EMOTING(DATA_FLAG_EMOTING),
    CELEBRATING(DATA_FLAG_CELEBRATING),
    ADMIRING(DATA_FLAG_ADMIRING),
    CELEBRATING_SPECIAL(DATA_FLAG_CELEBRATING_SPECIAL),
}
