name: IntelliMob
main: games.joserobjr.intellimob.IntelliMobPowerNukkitPlugin
version: 0.1.0-SNAPSHOT
api: ["1.0.11"]
load: STARTUP
author: joserobjr
website: https://github.com/joserobjr/IntelliMob
description: Giving intelligence to mobs on Minecraft Bedrock Edition servers written in Java
softdepend:
  - PowerNukkit
